version: "3.8"

services:
  database:
    image: postgres:15.0-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=db

  fast_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://test:test@database/db
    depends_on:
      - database
    restart: always
    volumes:
      - .:/usr/src


